[project]
name = "drygmock"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "tree-sitter>=0.25.2",
    "tree-sitter-cpp>=0.23.4",
]

[project.scripts]
drygmock = "main:main"
